name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  test:
    name: Server Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: 'windows-latest'

    steps:
    - name: Download Pragma (Windows)
      if: runner.os == 'Windows'
      run: |
        $repo = $env:GITHUB_REPOSITORY
        Invoke-WebRequest -Uri "https://github.com/$repo/releases/download/nightly/pragma-win64.zip" -OutFile "pragma-win64.zip"
        Expand-Archive -Path "pragma-win64.zip" -DestinationPath "pragma"

    - name: Run Test Scripts
      shell: bash
      run: |
        cd "pragma"
        ./pragma_server -luaext -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
        EXIT_CODE=$?
        # Check the exit code
        if [ $EXIT_CODE -eq 0 ]; then
          echo "Tests were successful."
        else
          echo "Tests have failed with exit code $EXIT_CODE."
          exit 1 # Exit the step with an error status
        fi

    - name: Check Result
      shell: bash
      run: |
        CI_CONTENTS=$(cat "pragma/ci.txt")
        if [ $exit_code -ne 0 ]; then
          exit $exit_code
        fi
        if [ "$CI_CONTENTS" == "0" ]; then
          echo "ci.txt contains '0'. Step failed."
          exit 1
        fi

    - name: Upload Log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: log_server
        path: "pragma/log_server.txt"
